apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmaster.fullname" . }}-web
  labels: {{- include "openmaster.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels: {{- include "openmaster.selectorLabels" (dict "root" . "component" "web") | nindent 6 }}
  template:
    metadata:
      labels: {{- include "openmaster.componentLabels" (dict "root" . "component" "web") | nindent 8 }}
    spec:
      serviceAccountName: {{ include "openmaster.fullname" . }}
      automountServiceAccountToken: false
      securityContext: {{- toYaml .Values.web.podSecurityContext | nindent 8 }}
      containers:
        - name: web
          image: {{ default (include "openmaster.image" .) .Values.web.image | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{name: http, containerPort: 8080}]
          resources: {{- toYaml .Values.web.resources | nindent 12 }}
          securityContext: {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          readinessProbe:
            httpGet: {path: /, port: http}
            {{- toYaml .Values.web.probes.readiness | nindent 12 }}
          livenessProbe:
            httpGet: {path: /, port: http}
            {{- toYaml .Values.web.probes.liveness | nindent 12 }}
          volumeMounts:
            - {name: tmp, mountPath: /tmp}
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: {{ .Values.temporaryStorage.sizeLimit }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openmaster.fullname" . }}-web
  labels: {{- include "openmaster.componentLabels" (dict "root" . "component" "web") | nindent 4 }}
spec:
  selector: {{- include "openmaster.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports: [{name: http, port: 80, targetPort: http}]
