apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: openmaster
spec:
  externalSecretName: openmaster
  namespaceSelectors:
    - matchLabels:
        openmaster.io/secrets: "enabled"
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: vault-global
    target:
      name: openmaster-secrets
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: REPLACE_WITH_VAULT_PATH
