global:
  environment: production

image:
  registry: harbor.lucaslamy.fr
  repository: private/openmaster
  tag: "3.6.1-layered"

externalSecrets:
  enabled: true
  existingSecretName: openmaster-secrets

ingress:
  enabled: true
  className: traefik
  host: openmaster.lucaslamy.fr
  tls:
    enabled: true
    secretName: openmaster-tls

api:
  image: harbor.lucaslamy.fr/private/openmaster/api:3.6.1-layered
  replicaCount: 2

web:
  image: harbor.lucaslamy.fr/private/openmaster/web:3.6.1-layered
  replicaCount: 2

workers:
  image: harbor.lucaslamy.fr/private/openmaster/api:3.6.1-layered

postgresql:
  persistence:
    storageClassName: longhorn

minio:
  enabled: false
  externalHost: minio.clipforge.svc.cluster.local
  externalPort: 9000
  externalPublicEndpoint: https://s3.lucaslamy.fr
  externalNetworkPolicy:
    namespaceSelector:
      kubernetes.io/metadata.name: clipforge
    podSelector:
      app: minio
  publicIngress:
    enabled: false

autoscaling:
  enabled: true
  api:
    minReplicas: 2
  workers:
    analysis:
      minReplicas: 2
    mastering:
      minReplicas: 2
    export:
      minReplicas: 2

podDisruptionBudget:
  enabled: true

remoteCompute:
  enabled: false
